# General Jekyll Config
name: CCSU Senior Project
title: CCSU Senior Project
description: Fall 2020
url: https://github.com/brignano/ccsu-senior-project-fall-2020/
lsi: false

author: Anthony Brignano
email: anthony.brignano@thehartford.com

# If you want to link only specific pages in your header/aside, uncomment 
# this and add the path to the pages in order as they should show up 
header_pages: 
 - README.md
 - Scope.md
 - Guidebook.md
 - References.md
 
# Defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: "swe-default"

# Build settings
remote_theme: thehartford/minima

# Plugins
plugins:
 - jekyll-feed
 - jekyll-seo-tag
